---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: default-allow
  namespace: app
spec:
  endpointSelector: {}
  egress:
  - toEndpoints: 
  - {}
  - toEndpoints:
      - matchLabels:
          io.kubernetes.pod.namespace: kube-system
          k8s-app: kube-dns
  ingress:
  - fromEndpoints:
    - {}
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: default-allow
  namespace: data
spec:
  endpointSelector: {}
  egress:
  - toEndpoints:
    - {}
  - toEndpoints:
      - matchLabels:
          io.kubernetes.pod.namespace: kube-system
          k8s-app: kube-dns
  ingress:
  - fromEndpoints:
    - {}